# Generated by Django 3.2.6 on 2021-08-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='health_and_phisical_education',
            new_name='health_and_physical_education',
        ),
        migrations.RenameField(
            model_name='grades',
            old_name='technical_arts_and_home_economies',
            new_name='technical_arts_and_home_economics',
        ),
    ]
