# Generated by Django 3.2.6 on 2021-08-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_management', '0002_auto_20210822_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='school_year',
            field=models.IntegerField(default=1, verbose_name='学年'),
            preserve_default=False,
        ),
    ]
