# Generated by Django 3.2.6 on 2021-08-26 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_management', '0003_grades_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='art',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='美術'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='english',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='英語'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='health_and_physical_education',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='保健体育'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='math',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='数学'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='music',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='音楽'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='national_language',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='国語'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='school_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='学年'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='science',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='理科'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='semester',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='学期'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='social_studies',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='社会'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='technical_arts_and_home_economics',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='技術・家庭科'),
        ),
    ]
