# Generated by Django 3.2.6 on 2021-08-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looking_back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_passport01_1',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
