# Generated by Django 3.2.6 on 2021-11-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('looking_back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career_passport01_1',
            name='UniqueID',
        ),
        migrations.DeleteModel(
            name='career_passport02',
        ),
        migrations.DeleteModel(
            name='career_passport03',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='career_passport01_1',
        ),
    ]
