# Generated by Django 3.2.6 on 2021-08-22 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('looking_back', '0002_alter_career_passport01_1_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(verbose_name='学期')),
                ('regular_test', models.CharField(max_length=2, verbose_name='中間または期末')),
                ('national_language', models.IntegerField(verbose_name='国語')),
                ('math', models.IntegerField(verbose_name='数学')),
                ('english', models.IntegerField(verbose_name='英語')),
                ('social_studies', models.IntegerField(verbose_name='社会')),
                ('science', models.IntegerField(verbose_name='理科')),
                ('music', models.IntegerField(verbose_name='音楽')),
                ('art', models.IntegerField(verbose_name='美術')),
                ('technical_arts_and_home_economies', models.IntegerField(verbose_name='技術・家庭科')),
                ('health_and_phisical_education', models.IntegerField(verbose_name='保健体育')),
                ('UniqueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'test_results',
            },
        ),
    ]
