# Generated by Django 3.2.6 on 2021-08-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('looking_back', '0003_grades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='grades',
        ),
    ]
