# Generated by Django 3.2.6 on 2021-10-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_alter_customuser_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytype',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='type_name',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='category_type',
            field=models.ManyToManyField(blank=True, to='accounts.CategoryType'),
        ),
    ]
