# Generated by Django 3.2.6 on 2021-08-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210822_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='share_ID',
            new_name='school_share_ID',
        ),
        migrations.AddField(
            model_name='customuser',
            name='parents_share_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
