# Generated by Django 3.2.6 on 2021-08-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210826_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='Parents_ID',
            new_name='parents_ID',
        ),
    ]
