# Generated by Django 3.2.6 on 2021-08-26 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_parents_id_parents_parents_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parents',
            options={'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name_plural': 'School'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teacher'},
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='homeroom_class',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
