# Generated by Django 3.2.6 on 2021-10-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211024_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'verbose_name_plural': 'CategoryType',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='category_type',
            field=models.ManyToManyField(blank=True, to='accounts.CategoryType'),
        ),
    ]
