# Generated by Django 3.2.6 on 2021-12-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesave',
            name='event_name',
            field=models.IntegerField(choices=[(1, 'イベント1'), (2, 'イベント2'), (3, 'イベント3')]),
        ),
    ]
