# Generated by Django 3.2.6 on 2021-12-14 08:57

import django.core.validators
from django.db import migrations, models
import file_uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploader', '0002_alter_filesave_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesave',
            name='file',
            field=models.ImageField(upload_to=file_uploader.models.save_select_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='filesave',
            name='semester',
            field=models.IntegerField(choices=[(1, '1学期'), (2, '2学期'), (3, '3学期')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='filesave',
            name='title',
            field=models.CharField(choices=[('title_1', 'タイトル1'), ('title_2', 'タイトル2'), ('title_3', 'タイトル3'), ('title_4', 'タイトル4'), ('title_5', 'タイトル5'), ('title_6', 'タイトル6'), ('title_7', 'タイトル7'), ('title_8', 'タイトル8')], max_length=100),
        ),
    ]
